defaults:
  - training_hyperparams: default_train_params
  - _self_

# >>> DATASET <<<
dataset_params:
  train_dataset_params:
    transforms:
      # for more options see common.factories.transforms_factory.py
      - SegColorJitter:
          brightness: 0.5
          contrast: 0.5
          saturation: 0.5

      - SegRandomFlip:
          prob: 0.5

      - SegRandomRescale:
          scales: [ 0.125, 1.5 ]

      - SegPadShortToCropSize:
          crop_size: [ 1024, 512 ]
          fill_mask: 19                  # ignored label idx

      - SegCropImageAndMask:
          crop_size: [ 1024, 512 ]
          mode: random

  val_dataset_params:
    transforms:
      - SegRescale:
          scale_factor: 0.5

  train_dataloader_params:
    shuffle: True
    batch_size: 8
    num_workers: 8
    drop_last: True

  val_dataloader_params:
    batch_size: 8
    num_workers: 8
    drop_last: False

# >>> ARCHITECTURE <<<
architecture: pp_lite_t_seg
arch_params:
  num_classes: 34
  use_aux_heads: True


# >>> CHECKPOINT <<<
checkpoint_params:
  load_weights_only: True
  strict_load: no_key_matching
  load_checkpoint: False # whether to load checkpoint
  load_backbone: False # whether to load only backbone part of checkpoint
  checkpoint_path: # checkpoint path that is located in super_gradients/checkpoints
  external_checkpoint_path: # checkpoint path that is not located in super_gradients/checkpoints
  source_ckpt_folder_name: # dirname for checkpoint loading
  pretrained_weights: # a string describing the dataset of the pretrained weights (for example "imagenent").


training_hyperparams:
  max_epochs: 800
  lr_mode: poly
  initial_lr: 0.01   # for effective batch_size=32
  lr_warmup_epochs: 10
  multiply_head_lr: 10.

  optimizer: SGD
  optimizer_params:
    momentum: 0.9
    weight_decay: 5e-4

  ema: True
  ema_params:
    decay: 0.9999
    beta: 15
    exp_activation: True

  train_metrics_list:
    - PixelAccuracy:
        ignore_label: 19
    - IoU:
        num_classes: 35
        ignore_index: 19

  valid_metrics_list:
    - PixelAccuracy:
        ignore_label: 19
    - IoU:
        num_classes: 35
        ignore_index: 19



  zero_weight_decay_on_bias_and_bn: True
  average_best_models: True
  mixed_precision: False

  metric_to_watch: IoU
  greater_metric_to_watch_is_better: True
  sync_bn: True
  loss:
    dice_ce_edge_loss:
      num_classes: 34
      ignore_index: 19
      num_aux_heads: 3
      num_detail_heads: 0
      weights: [ 1., 1., 1., 1. ]
      dice_ce_weights: [ 1., 1. ]
      ce_edge_weights: [ .5, .5 ]
      edge_kernel: 5

multi_gpu: DDP
num_gpus: 4

experiment_name: ${architecture}50_cityscapes
ckpt_root_dir:


# THE FOLLOWING PARAMS ARE DIRECTLY USED BY HYDRA
hydra:
  run:
    # Set the output directory (i.e. where .hydra folder that logs all the input params will be generated)
    dir: ${hydra_output_dir:${ckpt_root_dir}, ${experiment_name}}
