defaults:
  - default_train_params

max_epochs: 500

initial_lr:  0.01
warmup_mode: "linear_step"
warmup_initial_lr: 0.0001
lr_warmup_epochs: 5

lr_mode: cosine
cosine_final_lr_ratio: 0.05

zero_weight_decay_on_bias_and_bn: False
batch_accumulate: 1

save_ckpt_epoch_list: [285]

loss:
  ppyoloe_loss:
    num_classes: ${arch_params.num_classes}
    reg_max: ${arch_params.head.reg_max}

optimizer: SGD
optimizer_params:
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: False

compute_losses_on_valid: False
static_assigner_end_epoch: 100

#ema: True
#ema_params:
#  decay: 0.9998
#  decay_function:
#    constant:

mixed_precision: False
sync_bn: True

valid_metrics_list:
  - DetectionMetrics:
      score_thres: 0.1
      top_k_predictions: 300
      normalize_targets: True
      post_prediction_callback:
        _target_: super_gradients.training.models.detection_models.pp_yolo_e.PPYoloEPostPredictionCallback
        nms_threshold: 0.7
        score_threshold: 0.01
        nms_top_k: 1000
        max_predictions: 300
      num_cls: ${arch_params.num_classes}

pre_prediction_callback:

phase_callbacks:
  - PPYoloETrainingStageSwitchCallback:
      static_assigner_end_epoch: ${training_hyperparams.static_assigner_end_epoch}

  - DetectionVisualizationCallback:
      phase:
        _target_: super_gradients.training.utils.callbacks.callbacks.Phase
        value: VALIDATION_BATCH_END

      freq: 1
      batch_idx: 0
      classes:
        - "person"
        - "bicycle"
        - "car"
        - "motorcycle"
        - "airplane"
        - "bus"
        - "train"
        - "truck"
        - "boat"
        - "traffic light"
        - "fire hydrant"
        - "stop sign"
        - "parking meter"
        - "bench"
        - "bird"
        - "cat"
        - "dog"
        - "horse"
        - "sheep"
        - "cow"
        - "elephant"
        - "bear"
        - "zebra"
        - "giraffe"
        - "backpack"
        - "umbrella"
        - "handbag"
        - "tie"
        - "suitcase"
        - "frisbee"
        - "skis"
        - "snowboard"
        - "sports ball"
        - "kite"
        - "baseball bat"
        - "baseball glove"
        - "skateboard"
        - "surfboard"
        - "tennis racket"
        - "bottle"
        - "wine glass"
        - "cup"
        - "fork"
        - "knife"
        - "spoon"
        - "bowl"
        - "banana"
        - "apple"
        - "sandwich"
        - "orange"
        - "broccoli"
        - "carrot"
        - "hot dog"
        - "pizza"
        - "donut"
        - "cake"
        - "chair"
        - "couch"
        - "potted plant"
        - "bed"
        - "dining table"
        - "toilet"
        - "tv"
        - "laptop"
        - "mouse"
        - "remote"
        - "keyboard"
        - "cell phone"
        - "microwave"
        - "oven"
        - "toaster"
        - "sink"
        - "refrigerator"
        - "book"
        - "clock"
        - "vase"
        - "scissors"
        - "teddy bear"
        - "hair drier"
        - "toothbrush"
      post_prediction_callback:
        _target_: super_gradients.training.models.detection_models.pp_yolo_e.PPYoloEPostPredictionCallback
        nms_threshold: 0.7
        score_threshold: 0.5
        nms_top_k: 1000
        max_predictions: 300


metric_to_watch: 'mAP@0.50:0.95'
greater_metric_to_watch_is_better: True

_convert_: all
