defaults:
  - default_train_params

max_epochs: 300
lr_mode: cosine
cosine_final_lr_ratio: 0.05
lr_warmup_epochs: 5
lr_cooldown_epochs: 15
warmup_bias_lr: 0.0
warmup_momentum: 0.9
initial_lr: 0.01
warmup_mode: yolov5_warmup

save_ckpt_epoch_list: [285]

loss: yolox_loss
criterion_params: ??? # will be overridden in train conf as it includes sg_model
loss_logging_items_names: [iou, obj, cls, l1, num_fg, Loss]

optimizer: SGD
optimizer_params:
  momentum: 0.9
  weight_decay: 0.0005  # will be scaled according to effective batch size
  nesterov: True

ema: True
mixed_precision: False

valid_metrics_list:
  - _target_: super_gradients.training.metrics.DetectionMetrics
    post_prediction_callback:
      _target_: super_gradients.training.models.detection_models.yolov5_base.YoloV5PostPredictionCallback
    num_cls: 80

metric_to_watch: 'mAP@0.50:0.95'
greater_metric_to_watch_is_better: True

_convert_: all
