defaults:
  - default_train_params

max_epochs: 300

warmup_mode: "linear_batch_step"
warmup_initial_lr:  1e-6
lr_warmup_steps: 1000
lr_warmup_epochs: 0

initial_lr:  2e-4
lr_mode: cosine
cosine_final_lr_ratio: 0.1

zero_weight_decay_on_bias_and_bn: True
batch_accumulate: 1

average_best_models: True
save_ckpt_epoch_list: [100, 200, 250]

loss: yolo_nas_pose_loss

criterion_params:
    num_classes: ${arch_params.num_classes}
    reg_max: 16
    oks_sigmas: ${dataset_params.oks_sigmas}
    classification_loss_weight: 0.5
    classification_loss_type: focal
    regression_iou_loss_type: giou
    iou_loss_weight: 7.5
    dfl_loss_weight: 1.5
    pose_cls_loss_weight: 1.0
    pose_reg_loss_weight: 12.0
    rescale_keypoint_loss_by_assigned_weight: False
    use_cocoeval_formula: True
    pose_classification_loss_type: bce

optimizer: AdamW
optimizer_params:
  weight_decay: 0.000001

ema: False
ema_params:
  decay: 0.9997
  decay_type: threshold

mixed_precision: True
sync_bn: False

valid_metrics_list:
  - PoseEstimationMetrics:
      num_joints: ${dataset_params.num_joints}
      oks_sigmas: ${dataset_params.oks_sigmas}
      max_objects_per_image: 30
      post_prediction_callback:
        _target_: super_gradients.training.models.pose_estimation_models.yolo_nas_pose.YoloNASPosePostPredictionCallback
        keypoint_confidence_threshold: 0.5
        pose_confidence_threshold: 0.1
        nms_iou_threshold: 0.7
        pre_nms_max_predictions: 300
        post_nms_max_predictions: 30


phase_callbacks:
  - ExtremeBatchPoseEstimationVisualizationCallback:
      keypoint_colors: ${dataset_params.keypoint_colors}
      edge_colors: ${dataset_params.edge_colors}
      edge_links: ${dataset_params.edge_links}
      loss_to_monitor: YoloNASPoseLoss/loss
      max: True
      freq: 1
      max_images: 16
      enable_on_train_loader: True
      enable_on_valid_loader: True
      post_prediction_callback:
        _target_: super_gradients.training.models.pose_estimation_models.yolo_nas_pose.YoloNASPosePostPredictionCallback
        keypoint_confidence_threshold: 0.5
        pose_confidence_threshold: 0.1
        nms_iou_threshold: 0.7
        pre_nms_max_predictions: 300
        post_nms_max_predictions: 30

pre_prediction_callback:

metric_to_watch: 'AP'
greater_metric_to_watch_is_better: True

_convert_: all
