site_name: super-gradients
nav:
- Welcome:
  - Intro: ./README.md
  - Installation : ./documentation/source/installation.md
  - Model Zoo: ./src/super_gradients/training/Computer_Vision_Models_Pretrained_Checkpoints.md
- Quick Start:
  - Basic: ./documentation/source/QuickstartBasicToolkit.md
  - Classification: ./documentation/assets/Example_Classification.md
  - Segmentation: ./documentation/source/Segmentation.md
  - Pose Estimation: ./documentation/source/PoseEstimation.md
  - Training an external model: ./documentation/assets/Example_Training-an-external-model.md
- Tutorials:
  - Models: ./documentation/source/models.md
  - Dataset:
    - Data: ./documentation/source/Data.md
    - Computer Vision Datasets: ./src/super_gradients/training/datasets/Dataset_Setup_Instructions.md
  - Loss functions: ./documentation/assets/Losses.md
  - LR schedulers: ./documentation/source/LRScheduling.md
  - Metrics: ./documentation/source/Metrics.md
  - Optimizers: ./documentation/source/optimizers.md
  - Phase Callbacks: ./documentation/source/PhaseCallbacks.md
  - YAMLs and Recipes: 
    - Configurations: ./documentation/source/configuration_files.md
    - Recipes: ./src/super_gradients/recipes/Training_Recipes.md
  - Checkpoints: ./documentation/source/Checkpoints.md
- Features:
  - Training Modes: ./documentation/source/device.md
  - Logging: ./documentation/source/logs.md
  - Experiment Monitoring: ./documentation/source/experiment_monitoring.md
  - EMA: ./documentation/source/EMA.md
  - AMP: ./documentation/source/average_mixed_precision.md
  - Knowledge Distillation: ./documentation/source/KD.md
  - 'PTQ & QAT': ./documentation/source/ptq_qat.md
- Troubleshooting: ./documentation/source/troubleshooting.md
- Contribution: ./documentation/source/CONTRIBUTING.md
- Code: this_is_automatically_generated.md
