s -lte_name: super-gradients
nav:
- Welcome:
  - Intro: ./README.md
  - Model Zoo: ./src/super_gradients/training/Computer_Vision_Models_Pretrained_Checkpoints.md
- Quick Start:
  - Segmentation: ./documentation/source/Segmentation.md
- Tutorials:
  - Models: ./documentation/source/models.md
  - Dataset:
    - Data: ./documentation/source/Data.md
    - Computer Vision Datasets: ./src/super_gradients/training/datasets/Dataset_Setup_Instructions.md
  - Metrics: ./documentation/source/Metrics.md
  - Optimizers: ./documentation/source/optimizers.md
  - Phase Callbacks: ./documentation/source/PhaseCallbacks.md
  - YAMLs and Recipes: ./documentation/source/configuration_files.md
- Features:
  - Training Modes: ./documentation/source/device.md
  - Logging: ./documentation/source/logs.md
  - Experiment Monitoring: ./documentation/source/experiment_monitoring.md
  - EMA: ./documentation/source/EMA.md
  - AMP: ./documentation/source/average_mixed_precision.md
- Contribution: ./documentation/source/CONTRIBUTING.md
- Code: this_is_automatically_generated.md
