defaults:
  - yolo_arch_params

anchors:
  _target_: super_gradients.training.utils.detection_utils.Anchors
  anchors_list: [[], [], []]
  strides: [8, 16, 32]

yolo_type: 'pp_yolo_e'

depth_mult_factor: 1.33
width_mult_factor: 1.25
