defaults:
  - yolo_arch_params

anchors:
  _target_: super_gradients.training.utils.detection_utils.Anchors
  anchors_list: [[10, 13, 16, 30, 33, 23],[30, 61, 62, 45, 59, 119],[116, 90, 156, 198, 373, 326]]
  strides: [8, 16, 32]


yolo_type: 'yoloX'

depth_mult_factor: 0.33
width_mult_factor: 0.25