train_dataset_params:
  root_dir: /data/cityscapes
  list_file: lists/train.lst
  labels_csv_path: lists/labels.csv
  img_size: 1024
  cache_labels: False
  cache_images: False

  transforms:
    # for more options see common.factories.transforms_factory.py
    - ColorJitterSeg:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5

    - RandomFlipSeg:
        prob: 0.5

    - RandomRescaleSeg:
        scales: [ 0.5, 2. ]

    - PadShortToCropSizeSeg:
        crop_size: [ 2084, 1024 ]
        fill_mask: 19              # ignored label idx

    - CropImageAndMaskSeg:
        crop_size: [ 2084, 1024 ]
        mode: random

    - ToTensorSeg

    - NormalizeSeg:
        mean: [ .485, .456, .406 ]
        std: [ .229, .224, .225 ]


val_dataset_params:
  root_dir: /data/cityscapes
  list_file: lists/val.lst
  labels_csv_path: lists/labels.csv
  img_size: 1024
  cache_labels: False
  cache_images: False

  transforms:
    # for more options see common.factories.transforms_factory.py
    - NormalizeRGB:
        mean: [ .485, .456, .406 ]
        std: [ .229, .224, .225 ]

train_dataloader_params:
  batch_size: 8
  drop_last: True                 # drop the last incomplete batch, if dataset size is not divisible by the batch size

val_dataloader_params:
  batch_size: 8
  drop_last: False

_convert_: all
