defaults:
  - coco_pose_estimation_dataset_params
  - _self_

mosaic_prob: 0.8
dataset_params_suffix: "mosaic_${dataset_params.mosaic_prob}_${dataset_params.image_size}"

train_dataset_params:
  include_empty_samples: True
  min_instance_area: 1
  crowd_annotations_action: mask_as_normal

  transforms:
    - KeypointsRandomHorizontalFlip:
        flip_index: ${dataset_params.flip_indexes}
        prob: 0.5

    - KeypointsBrightnessContrast:
        brightness_range: [ 0.8, 1.2 ]
        contrast_range: [ 0.8, 1.2 ]
        prob: 0.5

    - KeypointsHSV:
        hgain: 20
        sgain: 20
        vgain: 20
        prob: 0.5

    - KeypointsRandomAffineTransform:
        max_rotation: 5
        min_scale: 0.75
        max_scale: 1.5
        max_translate: 0.1
        image_pad_value: 127
        mask_pad_value: 1
        prob: 0.75
        interpolation_mode: [0, 1, 2, 3, 4]

    - KeypointsMosaic:
        prob: ${dataset_params.mosaic_prob}

    - KeypointsLongestMaxSize:
        max_height: ${dataset_params.image_size}
        max_width: ${dataset_params.image_size}

    - KeypointsPadIfNeeded:
        min_height: ${dataset_params.image_size}
        min_width: ${dataset_params.image_size}
        image_pad_value: [127, 127, 127]
        mask_pad_value: 1
        padding_mode: center

    - KeypointsImageStandardize:
        max_value: 255


  target_generator:
    YoloNASPoseTargetsGenerator

val_dataset_params:
  include_empty_samples: True
  min_instance_area: 1
  transforms:
    - KeypointsLongestMaxSize:
        max_height: ${dataset_params.image_size}
        max_width: ${dataset_params.image_size}

    - KeypointsPadIfNeeded:
        min_height: ${dataset_params.image_size}
        min_width: ${dataset_params.image_size}
        image_pad_value: 127
        mask_pad_value: 1
        padding_mode: bottom_right

    - KeypointsImageStandardize:
        max_value: 255

  target_generator:
    YoloNASPoseTargetsGenerator

train_dataloader_params:
  pin_memory: False
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.YoloNASPoseTargetsCollateFN

val_dataloader_params:
  pin_memory: False
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.YoloNASPoseTargetsCollateFN
