defaults:
  - coco_pose_estimation_yolo_nas_mosaic_dataset_params
  - _self_

dataset_params_suffix: "mosaic_light_multiscale_augs_${dataset_params.mosaic_prob}_${dataset_params.image_size}"

train_dataset_params:
  transforms:
    - KeypointsRandomHorizontalFlip:
        flip_index: ${dataset_params.flip_indexes}
        prob: 0.5

    - KeypointsBrightnessContrast:
        brightness_range: [ 0.7, 1.3 ]
        contrast_range: [ 0.7, 1.3 ]
        prob: 0.75

    - KeypointsReverseImageChannels:
        prob: 0.1

    - KeypointsHSV:
        hgain: 25
        sgain: 25
        vgain: 25
        prob: 0.75

    - KeypointsRandomRotate90:
        prob: 0.25

    - KeypointsMosaic:
        prob: ${dataset_params.mosaic_prob}

#    - KeypointsLongestMaxSize:
#        max_height: ${dataset_params.image_size}
#        max_width: ${dataset_params.image_size}
#
#    - KeypointsPadIfNeeded:
#        min_height: ${dataset_params.image_size}
#        min_width: ${dataset_params.image_size}
#        image_pad_value: [ 127, 127, 127 ]
#        mask_pad_value: 1
#        padding_mode: center

    - KeypointsImageStandardize:
        max_value: 255

    - KeypointsRemoveSmallObjects:
        min_instance_area: 1
        min_visible_keypoints: 1

train_dataloader_params:
  dataset: COCOPoseEstimationDataset
  shuffle: True
  batch_size: 8
  num_workers: 8
  drop_last: True
  pin_memory: False
  collate_fn:
    MultiscaleYoloNASPoseCollateFN:
      random_resize_sizes: [ 320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768 ]
      random_resize_modes:
        - 0 # cv::INTER_NEAREST
        - 1 # cv::INTER_LINEAR
        - 2 # cv::INTER_CUBIC
        - 3 # cv::INTER_AREA
        - 4 # cv::INTER_LANCZOS4
