defaults:
  - coco_pose_estimation_dataset_params
  - _self_

train_dataset_params:
  include_empty_samples: True
  min_instance_area: 0
  target_generator:
    YoloNASPoseTargetsGenerator

val_dataset_params:
  include_empty_samples: True
  min_instance_area: 0
  target_generator:
    YoloNASPoseTargetsGenerator

train_dataloader_params:
  pin_memory: False
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.YoloNASPoseTargetsCollateFN

val_dataloader_params:
  pin_memory: False
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.YoloNASPoseTargetsCollateFN
