class_names: [
    Person
    Sneakers
    Chair
    Other Shoes
    Hat
    Car
    Lamp
    Glasses
    Bottle
    Desk
    Cup
    Street Lights
    Cabinet/shelf
    Handbag/Satchel
    Bracelet
    Plate
    Picture/Frame
    Helmet
    Book
    Gloves
    Storage box
    Boat
    Leather Shoes
    Flower
    Bench
    Potted Plant
    Bowl/Basin
    Flag
    Pillow
    Boots
    Vase
    Microphone
    Necklace
    Ring
    SUV
    Wine Glass
    Belt
    Monitor/TV
    Backpack
    Umbrella
    Traffic Light
    Speaker
    Watch
    Tie
    Trash bin Can
    Slippers
    Bicycle
    Stool
    Barrel/bucket
    Van
    Couch
    Sandals
    Basket
    Drum
    Pen/Pencil
    Bus
    Wild Bird
    High Heels
    Motorcycle
    Guitar
    Carpet
    Cell Phone
    Bread
    Camera
    Canned
    Truck
    Traffic cone
    Cymbal
    Lifesaver
    Towel
    Stuffed Toy
    Candle
    Sailboat
    Laptop
    Awning
    Bed
    Faucet
    Tent
    Horse
    Mirror
    Power outlet
    Sink
    Apple
    Air Conditioner
    Knife
    Hockey Stick
    Paddle
    Pickup Truck
    Fork
    Traffic Sign
    Balloon
    Tripod
    Dog
    Spoon
    Clock
    Pot
    Cow
    Cake
    Dinning Table
    Sheep
    Hanger
    Blackboard/Whiteboard
    Napkin
    Other Fish
    Orange/Tangerine
    Toiletry
    Keyboard
    Tomato
    Lantern
    Machinery Vehicle
    Fan
    Green Vegetables
    Banana
    Baseball Glove
    Airplane
    Mouse
    Train
    Pumpkin
    Soccer
    Skiboard
    Luggage
    Nightstand
    Tea pot
    Telephone
    Trolley
    Head Phone
    Sports Car
    Stop Sign
    Dessert
    Scooter
    Stroller
    Crane
    Remote
    Refrigerator
    Oven
    Lemon
    Duck
    Baseball Bat
    Surveillance Camera
    Cat
    Jug
    Broccoli
    Piano
    Pizza
    Elephant
    Skateboard
    Surfboard
    Gun
    Skating and Skiing shoes
    Gas stove
    Donut
    Bow Tie
    Carrot
    Toilet
    Kite
    Strawberry
    Other Balls
    Shovel
    Pepper
    Computer Box
    Toilet Paper
    Cleaning Products
    Chopsticks
    Microwave
    Pigeon
    Baseball
    Cutting/chopping Board
    Coffee Table
    Side Table
    Scissors
    Marker
    Pie
    Ladder
    Snowboard
    Cookies
    Radiator
    Fire Hydrant
    Basketball
    Zebra
    Grape
    Giraffe
    Potato
    Sausage
    Tricycle
    Violin
    Egg
    Fire Extinguisher
    Candy
    Fire Truck
    Billiards
    Converter
    Bathtub
    Wheelchair
    Golf Club
    Briefcase
    Cucumber
    Cigar/Cigarette
    Paint Brush
    Pear
    Heavy Truck
    Hamburger
    Extractor
    Extension Cord
    Tong
    Tennis Racket
    Folder
    American Football
    earphone
    Mask
    Kettle
    Tennis
    Ship
    Swing
    Coffee Machine
    Slide
    Carriage
    Onion
    Green beans
    Projector
    Frisbee
    Washing Machine/Drying Machine
    Chicken
    Printer
    Watermelon
    Saxophone
    Tissue
    Toothbrush
    Ice cream
    Hot-air balloon
    Cello
    French Fries
    Scale
    Trophy
    Cabbage
    Hot dog
    Blender
    Peach
    Rice
    Wallet/Purse
    Volleyball
    Deer
    Goose
    Tape
    Tablet
    Cosmetics
    Trumpet
    Pineapple
    Golf Ball
    Ambulance
    Parking meter
    Mango
    Key
    Hurdle
    Fishing Rod
    Medal
    Flute
    Brush
    Penguin
    Megaphone
    Corn
    Lettuce
    Garlic
    Swan
    Helicopter
    Green Onion
    Sandwich
    Nuts
    Speed Limit Sign
    Induction Cooker
    Broom
    Trombone
    Plum
    Rickshaw
    Goldfish
    Kiwi fruit
    Router/modem
    Poker Card
    Toaster
    Shrimp
    Sushi
    Cheese
    Notepaper
    Cherry
    Pliers
    CD
    Pasta
    Hammer
    Cue
    Avocado
    Hamimelon
    Flask
    Mushroom
    Screwdriver
    Soap
    Recorder
    Bear
    Eggplant
    Board Eraser
    Coconut
    Tape Measure/Ruler
    Pig
    Showerhead
    Globe
    Chips
    Steak
    Crosswalk Sign
    Stapler
    Camel
    Formula 1
    Pomegranate
    Dishwasher
    Crab
    Hoverboard
    Meat ball
    Rice Cooker
    Tuba
    Calculator
    Papaya
    Antelope
    Parrot
    Seal
    Butterfly
    Dumbbell
    Donkey
    Lion
    Urinal
    Dolphin
    Electric Drill
    Hair Dryer
    Egg tart
    Jellyfish
    Treadmill
    Lighter
    Grapefruit
    Game board
    Mop
    Radish
    Baozi
    Target
    French
    Spring Rolls
    Monkey
    Rabbit
    Pencil Case
    Yak
    Red Cabbage
    Binoculars
    Asparagus
    Barbell
    Scallop
    Noddles
    Comb
    Dumpling
    Oyster
    Table Tennis paddle
    Cosmetics Brush/Eyeliner Pencil
    Chainsaw
    Eraser
    Lobster
    Durian
    Okra
    Lipstick
    Cosmetics Mirror
    Curling
    Table Tennis
]

train_dataset_params:
  data_dir: /data/coco # root path to coco data
  subdir: images/train2017 # sub directory path of data_dir containing the train data.
  json_file: annotations/instances_train2017.json # path to coco train json file, data_dir/annotations/train_json_file.
  input_dim: [640, 640]
  cache_dir:
  cache: False
  cache_annotations: True
  ignore_empty_annotations: True
  max_samples:
  transforms:
    - DetectionRandomAffine:
        degrees: 0                    # rotation degrees, randomly sampled from [-degrees, degrees]
        translate: 0.25               # image translation fraction
        scales: [ 0.5, 1.5 ]          # random rescale range (keeps size by padding/cropping) after mosaic transform.
        shear: 0.0                    # shear degrees, randomly sampled from [-degrees, degrees]
        target_size:
        filter_box_candidates: True   # whether to filter out transformed bboxes by edge size, area ratio, and aspect ratio.
        wh_thr: 2                     # edge size threshold when filter_box_candidates = True (pixels)
        area_thr: 0.1                 # threshold for area ratio between original image and the transformed one, when when filter_box_candidates = True
        ar_thr: 20                    # aspect ratio threshold when filter_box_candidates = True
    - DetectionRGB2BGR:
        prob: 0.5
    - DetectionHSV:
        prob: 0.5                       # probability to apply HSV transform
        hgain: 18                       # HSV transform hue gain (randomly sampled from [-hgain, hgain])
        sgain: 30                       # HSV transform saturation gain (randomly sampled from [-sgain, sgain])
        vgain: 30                       # HSV transform value gain (randomly sampled from [-vgain, vgain])
    - DetectionHorizontalFlip:
        prob: 0.5                       # probability to apply horizontal flip
#    - DetectionMixup:
#        input_dim:
#        mixup_scale: [ 0.5, 1.5 ]         # random rescale range for the additional sample in mixup
#        prob: 0.5                       # probability to apply per-sample mixup
#        flip_prob: 0.5                  # probability to apply horizontal flip
    - DetectionPaddedRescale:
        input_dim: ${dataset_params.train_dataset_params.input_dim}
        pad_value: 114
    - DetectionStandardize:
        max_value: 255.
    - DetectionTargetsFormatTransform:
        output_format: LABEL_CXCYWH

  tight_box_rotation: False
  class_inclusion_list:
  max_num_samples:
  with_crowd: False

train_dataloader_params:
  batch_size: 25
  num_workers: 8
  shuffle: True
  drop_last: True
  pin_memory: True
  collate_fn: DetectionCollateFN

val_dataset_params:
  data_dir: /data/coco # root path to coco data
  subdir: images/val2017/ # sub directory path of data_dir containing the train data.
  json_file: annotations/instances_val2017.json # path to coco train json file, data_dir/annotations/train_json_file.
  input_dim: [636, 636]
  cache_dir:
  cache: False
  max_samples: 10000
  cache_annotations: True
  ignore_empty_annotations: True
  transforms:
    - DetectionRGB2BGR:
        prob: 1
    - DetectionPadToSize:
        output_size: [640, 640]
        pad_value: 114
    - DetectionStandardize:
        max_value: 255.
    - DetectionImagePermute
    - DetectionTargetsFormatTransform:
        input_dim: [640, 640]
        output_format: LABEL_CXCYWH
  tight_box_rotation: False
  class_inclusion_list:
  max_num_samples:
  with_crowd: True

val_dataloader_params:
  batch_size: 24
  num_workers: 8
  drop_last: False
  shuffle: False
  pin_memory: True
  collate_fn: CrowdDetectionCollateFN

_convert_: all
