defaults:
  - coco2017_yolo_nas_pose_s_new_head_mosaic

experiment_suffix: mosaic_fine_tune_${training_hyperparams.criterion_params.pose_cls_loss_weight}_${training_hyperparams.criterion_params.pose_reg_loss_weight}_dfl_${training_hyperparams.criterion_params.dfl_loss_weight}_${training_hyperparams.criterion_params.iou_loss_weight}_${training_hyperparams.criterion_params.classification_loss_weight}_${training_hyperparams.criterion_params.classification_loss_type}

checkpoint_params:
  # For training Yolo-NAS-S pose estimation model we use pretrained weights for Yolo-NAS-S object detection model.
  # By setting strict_load: key_matching we load only those weights that match the keys of the model.
  # checkpoint_path: https://sghub.deci.ai/models/yolo_nas_s_coco.pth
  # Fine tune
  checkpoint_path: /home/bloodaxe/develop/super-gradients/checkpoints/coco2017_yolo_nas_pose_new_head_s_mosaic_1.0_12.0_dfl_0.01_2.5_1.0_focal/RUN_20230902_153215_812529/ckpt_best.pth
  strict_load:
    _target_: super_gradients.training.sg_trainer.StrictLoad
    value: key_matching

training_hyperparams:
  initial_lr:  5e-4
  ema: True
