defaults:
  - coco2017_yolo_nas_pose_s
  - override training_hyperparams: coco2017_yolo_nas_pose_train_params_v2
  - override dataset_params: coco_pose_estimation_yolo_nas_mosaic_dataset_params
  - _self_

experiment_suffix: mosaic_v2_${training_hyperparams.criterion_params.pose_cls_loss_weight}_${training_hyperparams.criterion_params.pose_reg_loss_weight}_${training_hyperparams.criterion_params.dfl_loss_weight}_${training_hyperparams.criterion_params.iou_loss_weight}_${training_hyperparams.criterion_params.classification_loss_weight}_${training_hyperparams.criterion_params.classification_loss_type}

dataset_params:
  train_dataloader_params:
    batch_size: 48

  val_dataloader_params:
    batch_size: 48

training_hyperparams:
  initial_lr:  1e-3
  cosine_final_lr_ratio: 0.05

  criterion_params:
    num_classes: ${arch_params.num_classes}
    reg_max: 16
    oks_sigmas: ${dataset_params.oks_sigmas}
    classification_loss_weight: 1.0
    classification_loss_type: focal
    regression_iou_loss_type: ciou
    iou_loss_weight: 2.5
    dfl_loss_weight: 0.01
    pose_cls_loss_weight: 1.0
    pose_reg_loss_weight: 17.0
    use_cocoeval_formula: True
    pose_classification_loss_type: focal

  sg_logger: wandb_sg_logger
  sg_logger_params:
    api_server: https://wandb.research.deci.ai
    entity: super-gradients
    launch_tensorboard: false
    monitor_system: true
    project_name: PoseEstimation
    save_checkpoints_remote: true
    save_logs_remote: true
    save_tensorboard_remote: true
    tb_files_user_prompt: false
    tensorboard_port: null
