#
# python -m super_gradients.train_from_recipe --config-name=coco2017_pose_yolo_pose_s
#

defaults:
  - training_hyperparams: coco2017_dekr_pose_train_params
  - dataset_params: coco_pose_estimation_dekr_dataset_params
  - arch_params: yolo_nas_pose_s_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

architecture: yolo_nas_pose_s

multi_gpu: DDP
num_gpus: 8

experiment_suffix: ""
experiment_name: coco2017_${architecture}${experiment_suffix}

ckpt_root_dir:

train_dataloader: coco2017_pose_train
val_dataloader: coco2017_pose_val

arch_params:
  num_classes: ${dataset_params.num_joints}

checkpoint_params:
  # We start training by loading the weights of the pretrained model for detection task
  pretrained_weights: "coco"
  strict_load: key_matching

dataset_params:
  train_dataloader_params:
    batch_size: 32

  val_dataloader_params:
    batch_size: 32
