defaults:
  - coco2017_yolo_nas_pose_s
  - _self_
  - variable_setup

multi_gpu: Off
num_gpus: 1


dataset_params:
#  train_dataset_params:
#    transforms:
#      - KeypointsRandomHorizontalFlip:
#          flip_index: ${dataset_params.flip_indexes}
#          prob: 0.5
#
#      - Albumentations:
#          Compose:
#            bbox_params:
#              min_area: 1
#              min_visibility: 0
#              min_width: 0
#              min_height: 0
#              check_each_transform: True
#            keypoint_params:
#            transforms:
#              - RandomBrightnessContrast:
#                  brightness_limit: [-0.3, 0.3]
#                  contrast_limit: [-0.3, 0.3]
#                  p: 0.75
#              - HueSaturationValue:
#                  hue_shift_limit: 25
#                  sat_shift_limit: 25
#                  val_shift_limit: 25
#                  p: 0.75
#              - Affine:
#                  scale: [0.5, 1.5]
#                  translate_percent:
#                    x: [-0.1, 0.1]
#                    y: [-0.1, 0.1]
#                  rotate: [-5, 5]
#                  cval: [127, 127, 127]
#                  cval_mask: 1
#                  interpolation: 1
#                  p: 1
#
#      - KeypointsMosaic:
#          prob: ${dataset_params.mosaic_prob}
#
#      - Albumentations:
#          Compose:
#            bbox_params:
#              min_area: 1
#              min_visibility: 0
#              min_width: 0
#              min_height: 0
#              check_each_transform: True
#            keypoint_params:
#            transforms:
#              - LongestMaxSize:
#                  max_size: [640, 640]
#                  p: 1
#              - PadIfNeeded:
#                  min_height: 640
#                  min_width: 640
#                  border_mode: 0
#                  value: [127, 127, 127]
#                  mask_value: 1
#                  p: 1
#
#      - KeypointsReverseImageChannels:
#          prob: 0.5
#      - KeypointsImageStandardize:
#          max_value: 255
#      - KeypointsRemoveSmallObjects:
#          min_instance_area: 1
#          min_visible_keypoints: 1
#
#      - Albumentations:
#          Compose:
#            bbox_params:
#              min_area: 1
#              min_visibility: 0
#              min_width: 0
#              min_height: 0
#              check_each_transform: True
#            keypoint_params:
#            transforms:
#              - RandomBrightnessContrast:
#                  brightness_limit: [-0.3, 0.3]
#                  contrast_limit: [-0.3, 0.3]
#                  p: 0.75
#              - HueSaturationValue:
#                  hue_shift_limit: 25
#                  sat_shift_limit: 25
#                  val_shift_limit: 25
#                  p: 0.75
#              - Affine:
#                  scale: [0.5, 1.5]
#                  translate_percent:
#                    x: [-0.1, 0.1]
#                    y: [-0.1, 0.1]
#                  rotate: [-5, 5]
#                  cval: 127
#                  cval_mask: 1
#                  interpolation: 1
#                  p: 1

  val_dataset_params:
    transforms:
      - KeypointsRandomHorizontalFlip:
          flip_index: ${dataset_params.flip_indexes}
          prob: 0.5

      - Albumentations:
          Compose:
            bbox_params:
              min_area: 1
              min_visibility: 0
              min_width: 0
              min_height: 0
              check_each_transform: True
            keypoint_params:
            transforms:
              - RandomBrightnessContrast:
                  brightness_limit: [-0.3, 0.3]
                  contrast_limit: [-0.3, 0.3]
                  p: 0.75
              - HueSaturationValue:
                  hue_shift_limit: 25
                  sat_shift_limit: 25
                  val_shift_limit: 25
                  p: 0.75
              - Affine:
                  scale: [0.5, 1.5]
                  translate_percent:
                    x: [-0.1, 0.1]
                    y: [-0.1, 0.1]
                  rotate: [-5, 5]
                  cval: [127, 127, 127]
                  cval_mask: 1
                  interpolation: 1
                  p: 1

      - KeypointsMosaic:
          prob: ${dataset_params.mosaic_prob}

      - Albumentations:
          Compose:
            bbox_params:
              min_area: 1
              min_visibility: 0
              min_width: 0
              min_height: 0
              check_each_transform: True
            keypoint_params:
            transforms:
              - LongestMaxSize:
                  max_size: [640, 640]
                  p: 1
              - PadIfNeeded:
                  min_height: 640
                  min_width: 640
                  border_mode: 0
                  value: [127, 127, 127]
                  mask_value: 1
                  p: 1

      - KeypointsReverseImageChannels:
          prob: 0.5
      - KeypointsImageStandardize:
          max_value: 255
      - KeypointsRemoveSmallObjects:
          min_instance_area: 1
          min_visible_keypoints: 1

#    transforms:
#      - Albumentations:
#          Compose:
#            bbox_params:
#              min_area: 1
#              min_visibility: 0
#              min_width: 0
#              min_height: 0
#              check_each_transform: True
#            keypoint_params:
#            transforms:
#            - LongestMaxSize:
#                max_size: [640, 640]
#                p: 1
#            - PadIfNeeded:
#                min_height: 640
#                min_width: 640
#                border_mode: 0
#                value: [127, 127, 127]
#                mask_value: 1
#                p: 1
#      - KeypointsImageStandardize:
#          max_value: 255

  train_dataloader_params:
    num_workers: 0

  val_dataloader_params:
    num_workers: 0

training_hyperparams:
#  sg_logger: wandb_sg_logger
#  sg_logger_params:
#      entity: "super-gradients"
#      api_server: "https://wandb.research.deci.ai"
#      project_name: "PoseEstimation"
#      monitor_system: false
#      save_logs_remote: false
#      tensorboard_port: null
#      launch_tensorboard: true
#      tb_files_user_prompt: false
#      save_checkpoints_remote: false
#      save_tensorboard_remote: true

  phase_callbacks:
      - ExtremeBatchPoseEstimationVisualizationCallback:
          keypoint_colors: ${dataset_params.keypoint_colors}
          edge_colors: ${dataset_params.edge_colors}
          edge_links: ${dataset_params.edge_links}
          loss_to_monitor: YoloNASPoseLoss/loss
          max: True
          freq: 1
          max_images: 16
          enable_on_train_loader: True
          enable_on_valid_loader: True
          post_prediction_callback:
            _target_: super_gradients.training.models.pose_estimation_models.yolo_nas_pose.YoloNASPosePostPredictionCallback
            pose_confidence_threshold: 0.1
            nms_iou_threshold: 0.7
            pre_nms_max_predictions: 300
            post_nms_max_predictions: 30
