defaults:
  - training_hyperparams: coco2017_yolo_nas_pose_train_params
  - dataset_params: coco_pose_estimation_yolo_nas_mosaic_dataset_params
  - arch_params: pose_former_b5_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

architecture: pose_former_b5

multi_gpu: DDP
num_gpus: 8

experiment_suffix: ""
experiment_name: coco2017_pose_${architecture}${experiment_suffix}

ckpt_root_dir:

arch_params:
  num_classes: ${dataset_params.num_joints}

checkpoint_params:
  checkpoint_path: https://sghub.deci.ai/models/segformer_b5_cityscapes.pth
  strict_load:
    _target_: super_gradients.training.sg_trainer.StrictLoad
    value: key_matching

dataset_params:
  mosaic_prob: 0.5

  train_dataloader_params:
    batch_size: 6

  val_dataloader_params:
    batch_size: 6
