
defaults:
  - training_hyperparams: coco2017_yolo_nas_pose_train_params
  - dataset_params: coco_pose_estimation_yolo_nas_mosaic_dataset_params
  - arch_params: pose_former_b2_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

architecture: pose_former_b2

multi_gpu: DDP
num_gpus: 8

# Assemble experiment suffix
bbox_cls_loss_suffix: box_${training_hyperparams.criterion_params.classification_loss_type}_${training_hyperparams.criterion_params.classification_loss_weight}
bbox_reg_loss_suffix: ${training_hyperparams.criterion_params.regression_iou_loss_type}_${training_hyperparams.criterion_params.iou_loss_weight}_dfl_${training_hyperparams.criterion_params.dfl_loss_weight}
pose_cls_loss_suffix: pose_${training_hyperparams.criterion_params.pose_classification_loss_type}_${training_hyperparams.criterion_params.pose_cls_loss_weight}
pose_reg_loss_suffix: reg_${training_hyperparams.criterion_params.pose_reg_loss_weight}

head_suffix: ""
experiment_suffix: "ema_less_mosaic_rescale_loss_lr_focal"
experiment_name: coco2017_${architecture}_${bbox_cls_loss_suffix}_${bbox_reg_loss_suffix}_${pose_cls_loss_suffix}_${pose_reg_loss_suffix}_${head_suffix}_${dataset_params.dataset_params_suffix}${experiment_suffix}

ckpt_root_dir:

train_dataloader: coco2017_pose_train
val_dataloader: coco2017_pose_val

arch_params:
  num_classes: ${dataset_params.num_joints}

training_hyperparams:
  initial_lr: 1e-4

checkpoint_params:
  checkpoint_path: https://sghub.deci.ai/models/segformer_b2_cityscapes.pth
  strict_load:
    _target_: super_gradients.training.sg_trainer.StrictLoad
    value: key_matching

dataset_params:
  train_dataset_params:
    include_empty_samples: False

  train_dataloader_params:
    batch_size: 16

  val_dataloader_params:
    batch_size: 16
