defaults:
  - crowdpose_yolo_nas_pose_s
  - override dataset_params: crowdpose_proxy_yolo_nas_dataset_params

experiment_suffix: "proxy"

training_hyperparams:
  phase_callbacks: []
  initial_lr: 1e-4
  lr_warmup_steps: 128
  max_valid_batches: 32 # 32 * 96 = 3072 images per validation epoch

dataset_params:
  train_dataloader_params:
    batch_size: 96
    num_workers: 16

  val_dataloader_params:
    batch_size: 96
    num_workers: 16
