quantizer:
  OpenVinoQuantizer:
    quantizer_params:
      target_device: CPU
      preset: mixed

    selective_quantizer_params:
      skip_patterns: []

    calib_params:
      num_calib_batches: 128                # number of batches to use for calibration, if None whole dataloader will be used

exporter:
  OpenVinoExporter:
    output_path: ${architecture}_openvino_int8.xml

# Model-specific parameters
export_params:
    preprocessing: True
    postprocessing: True
    postprocessing_use_tensorrt_nms: False

    batch_size: 1
    confidence_threshold: 0.2
    onnx_simplify: True
    onnx_export_kwargs: {}

    detection_nms_iou_threshold: 0.5
    detection_max_predictions_per_image: 128
    detection_num_pre_nms_predictions: 1000
    detection_predictions_format: flat
